// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8mlA_GtrnHgcW4cthm-MorsqwEkZrugg',
    appId: '1:943531801651:web:ed861b59cb8abd0cf07746',
    messagingSenderId: '943531801651',
    projectId: 'r8r-app-fdd36',
    authDomain: 'r8r-app-fdd36.firebaseapp.com',
    storageBucket: 'r8r-app-fdd36.firebasestorage.app',
    measurementId: 'G-8NBVBRG3VH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCB9Gj70O84ksNt2RIdJnEaqNLnUlZqXLc',
    appId: '1:943531801651:android:dd6179807abb4de5f07746',
    messagingSenderId: '943531801651',
    projectId: 'r8r-app-fdd36',
    storageBucket: 'r8r-app-fdd36.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAfpphHUaGywrg-WYgVYpRFn7H9if8ixQ',
    appId: '1:943531801651:ios:1a75a7ccd8131011f07746',
    messagingSenderId: '943531801651',
    projectId: 'r8r-app-fdd36',
    storageBucket: 'r8r-app-fdd36.firebasestorage.app',
    iosBundleId: 'com.r8r.app.r8r',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAfpphHUaGywrg-WYgVYpRFn7H9if8ixQ',
    appId: '1:943531801651:ios:1a75a7ccd8131011f07746',
    messagingSenderId: '943531801651',
    projectId: 'r8r-app-fdd36',
    storageBucket: 'r8r-app-fdd36.firebasestorage.app',
    iosBundleId: 'com.r8r.app.r8r',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8mlA_GtrnHgcW4cthm-MorsqwEkZrugg',
    appId: '1:943531801651:web:17e8e456f7d40ac0f07746',
    messagingSenderId: '943531801651',
    projectId: 'r8r-app-fdd36',
    authDomain: 'r8r-app-fdd36.firebaseapp.com',
    storageBucket: 'r8r-app-fdd36.firebasestorage.app',
    measurementId: 'G-J2C4R0DL35',
  );

}